#!/bin/bash

protected_branch='(develop$)|(release_[.0-9].x$)'  

function run_test {
	# no push to master	
	current_branch=$(git rev-parse --abbrev-ref HEAD)
	if [[ $current_branch =~ $protected_branch ]]
	then
		echo "You can't push directly into $current_branch"
		exit 1
	else
		exit 0
	fi
}

case "${1}" in
    --about )
        echo "Prevent push into $current_branch."
        ;;
    * )
        run_test
        ;;
esac
